# image will be published to ghcr.io/<user>/<name>
name: kinoite-image
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/kinoite-nvidia
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - usr: /usr # copies config/files/usr into your image's /usr.
                  # put configuration files you want in /etc/ on a booted system 
                  # in /usr/etc/ in the image. read more in files module reference.
                  # TODO add config files

  - type: rpm-ostree
    install:
      # - rclone # TODO
      - qt5-qtimageformats
    remove:
      - firefox # default firefox removed in favor of flatpak
      - firefox-langpacks # langpacks needs to also be removed to prevent dependency problems
      - kwrite # kate is installed as well and kwrite just gets in the way
      - plasma-discover-notifier # updates are applied automatically, so the notifier is just in the way

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
    install:
      - Bottles: com.usebottles.bottles
      - GIMP: org.gimp.GIMP
      - Gwenview: org.kde.gwenview
      - Ktorrent: org.kde.ktorrent
      - Libreoffice: org.libreoffice.LibreOffice
      - Firefox: org.mozilla.firefox
      - Mpv: io.mpv.Mpv
      - Okular: org.kde.okular
      - Olympus: io.github.everestapi.Olympus
      - Prism Launcher: org.prismlauncher.PrismLauncher
      - ProtonVPN: com.protonvpn.www
      - Signal: org.signal.Signal
      - Spotify: com.spotify.Client
      - Steam: com.valvesoftware.Steam
      # - Proton-GE: com.valvesoftware.Steam.CompatibilityTool.Proton-GE # Package removed, will add again if it's back
      - ProtonUp-Qt: net.davidotek.pupgui2 # Replacement for proton-ge
      - Teams: com.github.IsmaelMartinez.teams_for_linux
      - Vesktop: dev.vencord.Vesktop
      - Xournalpp: com.github.xournalpp.xournalpp
      
  - type: akmods
    install:
      - openrgb # RGB support
      - xpadneo # Bluetooth Controller support
      
  - type: signing # this sets up the proper policy & signing files for signed images to work fully

