# image will be published to ghcr.io/<user>/<name>
name: kinoite-image
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/kinoite-nvidia
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: rpm-ostree
    install:
      # - rclone # TODO
      - qt6-qtimageformats
      - kf6-kimageformats
    remove:
      - firefox # default firefox removed in favor of flatpak
      - firefox-langpacks # langpacks needs to also be removed to prevent dependency problems
      - kwrite # kate is installed as well and kwrite just gets in the way
      - plasma-discover-notifier # updates are applied automatically, so the notifier is just in the way

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      install:
        - com.usebottles.bottles
        - org.gimp.GIMP
        - org.kde.gwenview
        - org.kde.ktorrent
        - org.libreoffice.LibreOffice
        - org.mozilla.firefox
        - io.mpv.Mpv
        - org.kde.okular
        - io.github.everestapi.Olympus
        - org.prismlauncher.PrismLauncher
        - com.protonvpn.www
        - org.signal.Signal
        - com.spotify.Client
        - com.valvesoftware.Steam
        - com.valvesoftware.Steam.CompatibilityTool.Proton-GE
        - com.github.IsmaelMartinez.teams_for_linux
        - dev.vencord.Vesktop
        - com.github.xournalpp.xournalpp
      
  - type: signing # this sets up the proper policy & signing files for signed images to work fully
